// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SteamHub.Api.Context;

#nullable disable

namespace SteamHub.Api.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250425194001_AddRequiredFieldsToUser")]
    partial class AddRequiredFieldsToUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SteamHub.Api.Entities.TestGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TestGames");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Roblox"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Minecraft"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Metin2"
                        });
                });

            modelBuilder.Entity("SteamHub.Api.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("PointsBalance")
                        .HasColumnType("real");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserRole")
                        .HasColumnType("int");

                    b.Property<float>("WalletBalance")
                        .HasColumnType("real");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "user1@gmail.com",
                            PointsBalance = 100f,
                            UserName = "User1",
                            UserRole = 0,
                            WalletBalance = 56f
                        },
                        new
                        {
                            UserId = 2,
                            Email = "user2@gmail.com",
                            PointsBalance = 45f,
                            UserName = "User2",
                            UserRole = 0,
                            WalletBalance = 78f
                        },
                        new
                        {
                            UserId = 3,
                            Email = "user3@gmail.com",
                            PointsBalance = 234f,
                            UserName = "User3",
                            UserRole = 0,
                            WalletBalance = 21f
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
