// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SteamHub.Api.Context;

#nullable disable

namespace SteamHub.Api.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250426161120_AddTagsAndRemoveTestGamesTable")]
    partial class AddTagsAndRemoveTestGamesTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SteamHub.Api.Entities.Tag", b =>
                {
                    b.Property<int>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TagId"));

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TagId");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            TagId = 1,
                            TagName = "Tag1"
                        },
                        new
                        {
                            TagId = 2,
                            TagName = "Rogue-Like"
                        },
                        new
                        {
                            TagId = 3,
                            TagName = "Third-Person Shooter"
                        },
                        new
                        {
                            TagId = 4,
                            TagName = "Multiplayer"
                        },
                        new
                        {
                            TagId = 5,
                            TagName = "Horror"
                        },
                        new
                        {
                            TagId = 6,
                            TagName = "First-Person Shooter"
                        },
                        new
                        {
                            TagId = 7,
                            TagName = "Action"
                        },
                        new
                        {
                            TagId = 8,
                            TagName = "Platformer"
                        },
                        new
                        {
                            TagId = 9,
                            TagName = "Adventure"
                        },
                        new
                        {
                            TagId = 10,
                            TagName = "Puzzle"
                        },
                        new
                        {
                            TagId = 11,
                            TagName = "Exploration"
                        },
                        new
                        {
                            TagId = 12,
                            TagName = "Sandbox"
                        },
                        new
                        {
                            TagId = 13,
                            TagName = "Survival"
                        },
                        new
                        {
                            TagId = 14,
                            TagName = "Arcade"
                        },
                        new
                        {
                            TagId = 15,
                            TagName = "RPG"
                        },
                        new
                        {
                            TagId = 16,
                            TagName = "Racing"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
