// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SteamHub.Api.Context;

#nullable disable

namespace SteamHub.Api.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GameTag", b =>
                {
                    b.Property<int>("GamesGameId")
                        .HasColumnType("int");

                    b.Property<int>("TagsTagId")
                        .HasColumnType("int");

                    b.HasKey("GamesGameId", "TagsTagId");

                    b.HasIndex("TagsTagId");

                    b.ToTable("GameTag");

                    b.HasData(
                        new
                        {
                            GamesGameId = 1,
                            TagsTagId = 1
                        },
                        new
                        {
                            GamesGameId = 1,
                            TagsTagId = 2
                        },
                        new
                        {
                            GamesGameId = 1,
                            TagsTagId = 3
                        },
                        new
                        {
                            GamesGameId = 2,
                            TagsTagId = 4
                        },
                        new
                        {
                            GamesGameId = 2,
                            TagsTagId = 5
                        },
                        new
                        {
                            GamesGameId = 2,
                            TagsTagId = 6
                        },
                        new
                        {
                            GamesGameId = 3,
                            TagsTagId = 7
                        },
                        new
                        {
                            GamesGameId = 3,
                            TagsTagId = 8
                        },
                        new
                        {
                            GamesGameId = 3,
                            TagsTagId = 9
                        });
                });

            modelBuilder.Entity("SteamHub.Api.Entities.Game", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GameId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("GameplayPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MinimumRequirements")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfRecentPurchases")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PublisherUserId")
                        .HasColumnType("int");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RecommendedRequirements")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RejectMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("TrailerPath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GameId");

                    b.HasIndex("PublisherUserId");

                    b.HasIndex("StatusId");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            GameId = 1,
                            Description = "An epic open-world RPG set in a mystical realm full of adventure, magic, and danger.",
                            Discount = 0.15m,
                            GameplayPath = "https://www.youtube.com/watch?v=AKXiKBnzpBQ",
                            ImagePath = "https://upload.wikimedia.org/wikipedia/en/5/5e/Elden_Ring_Box_art.jpg",
                            MinimumRequirements = "Intel i5-8400, 8GB RAM, GTX 1060",
                            Name = "Legends of Etheria",
                            NumberOfRecentPurchases = 1200,
                            Price = 49.99m,
                            PublisherUserId = 3,
                            Rating = 4.7m,
                            RecommendedRequirements = "Intel i7-8700K, 16GB RAM, RTX 2070",
                            RejectMessage = "rejected game",
                            StatusId = 2,
                            TrailerPath = "https://www.youtube.com/watch?v=E3Huy2cdih0"
                        },
                        new
                        {
                            GameId = 2,
                            Description = "A futuristic open-world RPG where you explore the neon-lit streets of Nightcity.",
                            Discount = 0.25m,
                            GameplayPath = "https://www.youtube.com/watch?v=8X2kIfS6fb8",
                            ImagePath = "https://upload.wikimedia.org/wikipedia/en/9/9f/Cyberpunk_2077_box_art.jpg",
                            MinimumRequirements = "Intel i5-3570K, 8GB RAM, GTX 780",
                            Name = "Cyberstrike 2077",
                            NumberOfRecentPurchases = 950,
                            Price = 59.99m,
                            PublisherUserId = 4,
                            Rating = 4.2m,
                            RecommendedRequirements = "Intel i7-4790, 12GB RAM, GTX 1060",
                            StatusId = 1,
                            TrailerPath = "https://www.youtube.com/watch?v=FknHjl7eQ6o"
                        },
                        new
                        {
                            GameId = 3,
                            Description = "Immerse yourself in the Viking age in this brutal and breathtaking action RPG.",
                            Discount = 0.10m,
                            GameplayPath = "https://www.youtube.com/watch?v=gncB1_e9n8E",
                            ImagePath = "https://upload.wikimedia.org/wikipedia/en/6/6d/Assassin%27s_Creed_Valhalla_cover.jpg",
                            MinimumRequirements = "Intel i5-4460, 8GB RAM, GTX 960",
                            Name = "Shadow of Valhalla",
                            NumberOfRecentPurchases = 780,
                            Price = 44.99m,
                            PublisherUserId = 3,
                            Rating = 4.5m,
                            RecommendedRequirements = "Intel i7-6700K, 16GB RAM, GTX 1080",
                            StatusId = 1,
                            TrailerPath = "https://www.youtube.com/watch?v=ssrNcwxALS4"
                        },
                        new
                        {
                            GameId = 4,
                            Description = "An action-adventure game set in the fantasy land of Hyrule, where players control Link to rescue Princess Zelda.",
                            Discount = 0.20m,
                            GameplayPath = "https://www.youtube.com/watch?v=0u8g1c2v4xE",
                            ImagePath = "https://m.media-amazon.com/images/I/71oHNyzdN1L.jpg",
                            MinimumRequirements = "Intel Core i5, 8GB RAM, GTX 960",
                            Name = "The Legend of Zelda",
                            NumberOfRecentPurchases = 1500,
                            Price = 59.99m,
                            PublisherUserId = 3,
                            Rating = 4.8m,
                            RecommendedRequirements = "Intel Core i7, 16GB RAM, GTX 1060",
                            StatusId = 1,
                            TrailerPath = "https://www.youtube.com/watch?v=0u8g1c2v4xE"
                        },
                        new
                        {
                            GameId = 5,
                            Description = "A puzzle game where you change the rules to solve challenges.",
                            Discount = 0.20m,
                            GameplayPath = "https://www.youtube.com/watch?v=dAiX8s-Eu7w",
                            ImagePath = "https://is5-ssl.mzstatic.com/image/thumb/Purple113/v4/9e/30/61/9e3061a5-b2f0-87ad-9e90-563f37729be5/source/256x256bb.jpg",
                            MinimumRequirements = "2GB RAM, 1.0GHz Processor",
                            Name = "Baba is You",
                            NumberOfRecentPurchases = 1500,
                            Price = 14.99m,
                            PublisherUserId = 1,
                            Rating = 4.8m,
                            RecommendedRequirements = "4GB RAM, 2.0GHz Processor",
                            StatusId = 0,
                            TrailerPath = "https://www.youtube.com/watch?v=z3_yA4HTJfs"
                        },
                        new
                        {
                            GameId = 6,
                            Description = "A farming simulation game where players can grow crops, raise animals, and build their farm.",
                            Discount = 0.20m,
                            GameplayPath = "https://www.youtube.com/watch?v=dAiX8s-Eu7w",
                            ImagePath = "https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/9e/30/61/9e3061a5-b2f0-87ad-9e90-563f37729be5/source/256x256bb.jpg",
                            MinimumRequirements = "2GB RAM, 1.0GHz Processor",
                            Name = "Stardew Valley",
                            NumberOfRecentPurchases = 1500,
                            Price = 14.99m,
                            PublisherUserId = 2,
                            Rating = 4.8m,
                            RecommendedRequirements = "4GB RAM, 2.0GHz Processor",
                            StatusId = 0,
                            TrailerPath = "https://www.youtube.com/watch?v=z3_yA4HTJfs"
                        });
                });

            modelBuilder.Entity("SteamHub.Api.Entities.GameStatus", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GameStatus");

                    b.HasData(
                        new
                        {
                            Id = 0,
                            Name = "Pending"
                        },
                        new
                        {
                            Id = 1,
                            Name = "Approved"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Rejected"
                        });
                });

            modelBuilder.Entity("SteamHub.Api.Entities.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<int>("CorrespondingGameId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsListed")
                        .HasColumnType("bit");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.HasKey("ItemId");

                    b.HasIndex("CorrespondingGameId");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            ItemId = 1,
                            CorrespondingGameId = 1,
                            Description = "A mystical blade imbued with ancient magic from Legends of Etheria.",
                            ImagePath = "https://cdn.example.com/etheria/ethereal-blade.jpg",
                            IsListed = true,
                            ItemName = "Ethereal Blade",
                            Price = 29.99f
                        },
                        new
                        {
                            ItemId = 7,
                            CorrespondingGameId = 1,
                            Description = "A mystical blade imbued with ancient magic from Legends of Etheria.",
                            ImagePath = "https://cdn.example.com/etheria/ethereal-blade.jpg",
                            IsListed = false,
                            ItemName = "pilfered ethereal blade",
                            Price = 29.99f
                        },
                        new
                        {
                            ItemId = 2,
                            CorrespondingGameId = 1,
                            Description = "An enchanted armour that protects the bearer in Legends of Etheria.",
                            ImagePath = "https://cdn.example.com/etheria/mystic-armour.jpg",
                            IsListed = true,
                            ItemName = "Mystic Armour",
                            Price = 39.99f
                        },
                        new
                        {
                            ItemId = 3,
                            CorrespondingGameId = 2,
                            Description = "A high-tech gauntlet to hack and crush foes in Cyberstrike 2077.",
                            ImagePath = "https://cdn.example.com/cyberstrike/gauntlet.jpg",
                            IsListed = true,
                            ItemName = "Cybernetic Gauntlet",
                            Price = 34.99f
                        },
                        new
                        {
                            ItemId = 4,
                            CorrespondingGameId = 2,
                            Description = "A visor that enhances your vision in the neon-lit battles of Cyberstrike 2077.",
                            ImagePath = "https://cdn.example.com/cyberstrike/neon-visor.jpg",
                            IsListed = true,
                            ItemName = "Neon Visor",
                            Price = 24.99f
                        },
                        new
                        {
                            ItemId = 5,
                            CorrespondingGameId = 3,
                            Description = "A mighty axe for the warriors of Shadow of Valhalla.",
                            ImagePath = "https://cdn.example.com/valhalla/viking-axe.jpg",
                            IsListed = true,
                            ItemName = "Viking Axe",
                            Price = 44.99f
                        },
                        new
                        {
                            ItemId = 6,
                            CorrespondingGameId = 3,
                            Description = "A robust shield forged for the bravest of fighters in Shadow of Valhalla.",
                            ImagePath = "https://cdn.example.com/valhalla/shield.jpg",
                            IsListed = true,
                            ItemName = "Valhalla Shield",
                            Price = 34.99f
                        });
                });

            modelBuilder.Entity("SteamHub.Api.Entities.ItemTrade", b =>
                {
                    b.Property<int>("TradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TradeId"));

                    b.Property<bool>("AcceptedByDestinationUser")
                        .HasColumnType("bit");

                    b.Property<bool>("AcceptedBySourceUser")
                        .HasColumnType("bit");

                    b.Property<int>("DestinationUserId")
                        .HasColumnType("int");

                    b.Property<int>("GameOfTradeId")
                        .HasColumnType("int");

                    b.Property<int>("SourceUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TradeDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TradeDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TradeStatus")
                        .HasColumnType("int");

                    b.HasKey("TradeId");

                    b.HasIndex("DestinationUserId");

                    b.HasIndex("GameOfTradeId");

                    b.HasIndex("SourceUserId");

                    b.ToTable("ItemTrades");

                    b.HasData(
                        new
                        {
                            TradeId = 1,
                            AcceptedByDestinationUser = false,
                            AcceptedBySourceUser = false,
                            DestinationUserId = 2,
                            GameOfTradeId = 1,
                            SourceUserId = 1,
                            TradeDate = new DateTime(2025, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TradeDescription = "Trade 1: John Doe offers Game1 to Michael John",
                            TradeStatus = 0
                        },
                        new
                        {
                            TradeId = 2,
                            AcceptedByDestinationUser = false,
                            AcceptedBySourceUser = true,
                            DestinationUserId = 4,
                            GameOfTradeId = 2,
                            SourceUserId = 3,
                            TradeDate = new DateTime(2025, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TradeDescription = "Trade 2: Jane Doe offers Game2 to Maria Elena",
                            TradeStatus = 0
                        },
                        new
                        {
                            TradeId = 3,
                            AcceptedByDestinationUser = true,
                            AcceptedBySourceUser = true,
                            DestinationUserId = 2,
                            GameOfTradeId = 1,
                            SourceUserId = 1,
                            TradeDate = new DateTime(2025, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TradeDescription = "Trade 1: John Doe offers Game1 to Michael John",
                            TradeStatus = 2
                        });
                });

            modelBuilder.Entity("SteamHub.Api.Entities.ItemTradeDetail", b =>
                {
                    b.Property<int>("TradeId")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<bool>("IsSourceUserItem")
                        .HasColumnType("bit");

                    b.HasKey("TradeId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("ItemTradeDetails");

                    b.HasData(
                        new
                        {
                            TradeId = 1,
                            ItemId = 1,
                            IsSourceUserItem = true
                        },
                        new
                        {
                            TradeId = 2,
                            ItemId = 2,
                            IsSourceUserItem = false
                        });
                });

            modelBuilder.Entity("SteamHub.Api.Entities.PointShopItem", b =>
                {
                    b.Property<int>("PointShopItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PointShopItemId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PointPrice")
                        .HasColumnType("float");

                    b.HasKey("PointShopItemId");

                    b.ToTable("PointShopItems");

                    b.HasData(
                        new
                        {
                            PointShopItemId = 1,
                            Description = "A cool blue background for your profile",
                            ImagePath = "https://picsum.photos/id/1/200/200",
                            ItemType = "ProfileBackground",
                            Name = "Blue Profile Background",
                            PointPrice = 1000.0
                        },
                        new
                        {
                            PointShopItemId = 2,
                            Description = "A vibrant red background for your profile",
                            ImagePath = "https://picsum.photos/id/20/200/200",
                            ItemType = "ProfileBackground",
                            Name = "Red Profile Background",
                            PointPrice = 1000.0
                        },
                        new
                        {
                            PointShopItemId = 3,
                            Description = "A golden frame for your avatar image",
                            ImagePath = "https://picsum.photos/id/30/200/200",
                            ItemType = "AvatarFrame",
                            Name = "Golden Avatar Frame",
                            PointPrice = 2000.0
                        },
                        new
                        {
                            PointShopItemId = 4,
                            Description = "A silver frame for your avatar image",
                            ImagePath = "https://picsum.photos/id/40/200/200",
                            ItemType = "AvatarFrame",
                            Name = "Silver Avatar Frame",
                            PointPrice = 1500.0
                        },
                        new
                        {
                            PointShopItemId = 5,
                            Description = "Express yourself with this happy emoticon",
                            ImagePath = "https://picsum.photos/id/50/200/200",
                            ItemType = "Emoticon",
                            Name = "Happy Emoticon",
                            PointPrice = 500.0
                        },
                        new
                        {
                            PointShopItemId = 6,
                            Description = "Express yourself with this sad emoticon",
                            ImagePath = "https://picsum.photos/id/60/200/200",
                            ItemType = "Emoticon",
                            Name = "Sad Emoticon",
                            PointPrice = 500.0
                        },
                        new
                        {
                            PointShopItemId = 7,
                            Description = "Cool gamer avatar for your profile",
                            ImagePath = "https://picsum.photos/id/70/200/200",
                            ItemType = "Avatar",
                            Name = "Gamer Avatar",
                            PointPrice = 1200.0
                        },
                        new
                        {
                            PointShopItemId = 8,
                            Description = "Stealthy ninja avatar for your profile",
                            ImagePath = "https://picsum.photos/id/80/200/200",
                            ItemType = "Avatar",
                            Name = "Ninja Avatar",
                            PointPrice = 1200.0
                        },
                        new
                        {
                            PointShopItemId = 9,
                            Description = "Space-themed mini profile",
                            ImagePath = "https://picsum.photos/id/90/200/200",
                            ItemType = "MiniProfile",
                            Name = "Space Mini-Profile",
                            PointPrice = 3000.0
                        },
                        new
                        {
                            PointShopItemId = 10,
                            Description = "Fantasy-themed mini profile",
                            ImagePath = "https://picsum.photos/id/100/200/200",
                            ItemType = "MiniProfile",
                            Name = "Fantasy Mini-Profile",
                            PointPrice = 3000.0
                        });
                });

            modelBuilder.Entity("SteamHub.Api.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            Id = 0,
                            Name = "User"
                        },
                        new
                        {
                            Id = 1,
                            Name = "Developer"
                        });
                });

            modelBuilder.Entity("SteamHub.Api.Entities.StoreTransaction", b =>
                {
                    b.Property<int>("StoreTransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StoreTransactionId"));

                    b.Property<float>("Amount")
                        .HasColumnType("real");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<bool>("WithMoney")
                        .HasColumnType("bit");

                    b.HasKey("StoreTransactionId");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId");

                    b.ToTable("StoreTransactions");

                    b.HasData(
                        new
                        {
                            StoreTransactionId = 1,
                            Amount = 49.99f,
                            Date = new DateTime(2025, 4, 27, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            GameId = 1,
                            UserId = 1,
                            WithMoney = true
                        },
                        new
                        {
                            StoreTransactionId = 2,
                            Amount = 59.99f,
                            Date = new DateTime(2025, 4, 27, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            GameId = 2,
                            UserId = 2,
                            WithMoney = false
                        });
                });

            modelBuilder.Entity("SteamHub.Api.Entities.Tag", b =>
                {
                    b.Property<int>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TagId"));

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TagId");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            TagId = 1,
                            TagName = "Tag1"
                        },
                        new
                        {
                            TagId = 2,
                            TagName = "Rogue-Like"
                        },
                        new
                        {
                            TagId = 3,
                            TagName = "Third-Person Shooter"
                        },
                        new
                        {
                            TagId = 4,
                            TagName = "Multiplayer"
                        },
                        new
                        {
                            TagId = 5,
                            TagName = "Horror"
                        },
                        new
                        {
                            TagId = 6,
                            TagName = "First-Person Shooter"
                        },
                        new
                        {
                            TagId = 7,
                            TagName = "Action"
                        },
                        new
                        {
                            TagId = 8,
                            TagName = "Platformer"
                        },
                        new
                        {
                            TagId = 9,
                            TagName = "Adventure"
                        },
                        new
                        {
                            TagId = 10,
                            TagName = "Puzzle"
                        },
                        new
                        {
                            TagId = 11,
                            TagName = "Exploration"
                        },
                        new
                        {
                            TagId = 12,
                            TagName = "Sandbox"
                        },
                        new
                        {
                            TagId = 13,
                            TagName = "Survival"
                        },
                        new
                        {
                            TagId = 14,
                            TagName = "Arcade"
                        },
                        new
                        {
                            TagId = 15,
                            TagName = "RPG"
                        },
                        new
                        {
                            TagId = 16,
                            TagName = "Racing"
                        });
                });

            modelBuilder.Entity("SteamHub.Api.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("PointsBalance")
                        .HasColumnType("real");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("WalletBalance")
                        .HasColumnType("real");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "johndoe@gmail.com",
                            PointsBalance = 100f,
                            RoleId = 0,
                            UserName = "John Doe",
                            WalletBalance = 56f
                        },
                        new
                        {
                            UserId = 2,
                            Email = "michaeljohn@gmail.com",
                            PointsBalance = 45f,
                            RoleId = 0,
                            UserName = "Michael John",
                            WalletBalance = 78f
                        },
                        new
                        {
                            UserId = 3,
                            Email = "janedoe@gmail.com",
                            PointsBalance = 234f,
                            RoleId = 1,
                            UserName = "Jane Doe",
                            WalletBalance = 21f
                        },
                        new
                        {
                            UserId = 4,
                            Email = "mariaelena@gmail.com",
                            PointsBalance = 34f,
                            RoleId = 1,
                            UserName = "Maria Elena",
                            WalletBalance = 455f
                        });
                });

            modelBuilder.Entity("SteamHub.Api.Entities.UserInventory", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AcquiredDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("UserId", "ItemId", "GameId");

                    b.HasIndex("GameId");

                    b.HasIndex("ItemId");

                    b.ToTable("UserInventories");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            ItemId = 1,
                            GameId = 1,
                            AcquiredDate = new DateTime(2025, 4, 27, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false
                        },
                        new
                        {
                            UserId = 1,
                            ItemId = 2,
                            GameId = 1,
                            AcquiredDate = new DateTime(2025, 4, 27, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false
                        },
                        new
                        {
                            UserId = 1,
                            ItemId = 3,
                            GameId = 2,
                            AcquiredDate = new DateTime(2025, 4, 27, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false
                        },
                        new
                        {
                            UserId = 1,
                            ItemId = 4,
                            GameId = 2,
                            AcquiredDate = new DateTime(2025, 4, 27, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false
                        },
                        new
                        {
                            UserId = 1,
                            ItemId = 6,
                            GameId = 3,
                            AcquiredDate = new DateTime(2025, 4, 27, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false
                        },
                        new
                        {
                            UserId = 1,
                            ItemId = 7,
                            GameId = 1,
                            AcquiredDate = new DateTime(2025, 4, 27, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false
                        },
                        new
                        {
                            UserId = 2,
                            ItemId = 6,
                            GameId = 3,
                            AcquiredDate = new DateTime(2025, 4, 27, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false
                        },
                        new
                        {
                            UserId = 2,
                            ItemId = 5,
                            GameId = 3,
                            AcquiredDate = new DateTime(2025, 4, 27, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false
                        },
                        new
                        {
                            UserId = 2,
                            ItemId = 7,
                            GameId = 1,
                            AcquiredDate = new DateTime(2025, 4, 27, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false
                        });
                });

            modelBuilder.Entity("SteamHub.Api.Entities.UserPointShopItemInventory", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("PointShopItemId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "PointShopItemId");

                    b.HasIndex("PointShopItemId");

                    b.ToTable("UserPointShopInventories");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            PointShopItemId = 1,
                            IsActive = false,
                            PurchaseDate = new DateTime(2025, 4, 27, 14, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UserId = 1,
                            PointShopItemId = 2,
                            IsActive = true,
                            PurchaseDate = new DateTime(2025, 4, 27, 14, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UserId = 1,
                            PointShopItemId = 5,
                            IsActive = false,
                            PurchaseDate = new DateTime(2025, 4, 27, 14, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UserId = 2,
                            PointShopItemId = 2,
                            IsActive = true,
                            PurchaseDate = new DateTime(2025, 4, 27, 14, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UserId = 2,
                            PointShopItemId = 6,
                            IsActive = false,
                            PurchaseDate = new DateTime(2025, 4, 27, 14, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UserId = 3,
                            PointShopItemId = 3,
                            IsActive = false,
                            PurchaseDate = new DateTime(2025, 4, 27, 14, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UserId = 3,
                            PointShopItemId = 4,
                            IsActive = true,
                            PurchaseDate = new DateTime(2025, 4, 27, 14, 30, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("SteamHub.Api.Entities.UsersGames", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<bool>("IsInCart")
                        .HasColumnType("bit");

                    b.Property<bool>("IsInWishlist")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPurchased")
                        .HasColumnType("bit");

                    b.HasKey("UserId", "GameId");

                    b.HasIndex("GameId");

                    b.ToTable("UsersGames");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            GameId = 1,
                            IsInCart = false,
                            IsInWishlist = true,
                            IsPurchased = false
                        },
                        new
                        {
                            UserId = 1,
                            GameId = 2,
                            IsInCart = false,
                            IsInWishlist = false,
                            IsPurchased = true
                        },
                        new
                        {
                            UserId = 1,
                            GameId = 3,
                            IsInCart = true,
                            IsInWishlist = false,
                            IsPurchased = false
                        },
                        new
                        {
                            UserId = 2,
                            GameId = 1,
                            IsInCart = false,
                            IsInWishlist = false,
                            IsPurchased = true
                        },
                        new
                        {
                            UserId = 2,
                            GameId = 3,
                            IsInCart = true,
                            IsInWishlist = false,
                            IsPurchased = false
                        });
                });

            modelBuilder.Entity("GameTag", b =>
                {
                    b.HasOne("SteamHub.Api.Entities.Game", null)
                        .WithMany()
                        .HasForeignKey("GamesGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SteamHub.Api.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SteamHub.Api.Entities.Game", b =>
                {
                    b.HasOne("SteamHub.Api.Entities.User", "Publisher")
                        .WithMany()
                        .HasForeignKey("PublisherUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SteamHub.Api.Entities.GameStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Publisher");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("SteamHub.Api.Entities.Item", b =>
                {
                    b.HasOne("SteamHub.Api.Entities.Game", "Game")
                        .WithMany("Items")
                        .HasForeignKey("CorrespondingGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("SteamHub.Api.Entities.ItemTrade", b =>
                {
                    b.HasOne("SteamHub.Api.Entities.User", "DestinationUser")
                        .WithMany()
                        .HasForeignKey("DestinationUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SteamHub.Api.Entities.Game", "GameOfTrade")
                        .WithMany()
                        .HasForeignKey("GameOfTradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SteamHub.Api.Entities.User", "SourceUser")
                        .WithMany()
                        .HasForeignKey("SourceUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("DestinationUser");

                    b.Navigation("GameOfTrade");

                    b.Navigation("SourceUser");
                });

            modelBuilder.Entity("SteamHub.Api.Entities.ItemTradeDetail", b =>
                {
                    b.HasOne("SteamHub.Api.Entities.Item", "Item")
                        .WithMany("ItemTradeDetails")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SteamHub.Api.Entities.ItemTrade", "ItemTrade")
                        .WithMany("ItemTradeDetails")
                        .HasForeignKey("TradeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("ItemTrade");
                });

            modelBuilder.Entity("SteamHub.Api.Entities.StoreTransaction", b =>
                {
                    b.HasOne("SteamHub.Api.Entities.Game", "Game")
                        .WithMany("StoreTransactions")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SteamHub.Api.Entities.User", "User")
                        .WithMany("StoreTransactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SteamHub.Api.Entities.User", b =>
                {
                    b.HasOne("SteamHub.Api.Entities.Role", "UserRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("SteamHub.Api.Entities.UserInventory", b =>
                {
                    b.HasOne("SteamHub.Api.Entities.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SteamHub.Api.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SteamHub.Api.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Item");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SteamHub.Api.Entities.UserPointShopItemInventory", b =>
                {
                    b.HasOne("SteamHub.Api.Entities.PointShopItem", "PointShopItem")
                        .WithMany("UserPointShopItemsInventory")
                        .HasForeignKey("PointShopItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SteamHub.Api.Entities.User", "User")
                        .WithMany("UserPointShopItemsInventory")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PointShopItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SteamHub.Api.Entities.UsersGames", b =>
                {
                    b.HasOne("SteamHub.Api.Entities.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SteamHub.Api.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SteamHub.Api.Entities.Game", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("StoreTransactions");
                });

            modelBuilder.Entity("SteamHub.Api.Entities.Item", b =>
                {
                    b.Navigation("ItemTradeDetails");
                });

            modelBuilder.Entity("SteamHub.Api.Entities.ItemTrade", b =>
                {
                    b.Navigation("ItemTradeDetails");
                });

            modelBuilder.Entity("SteamHub.Api.Entities.PointShopItem", b =>
                {
                    b.Navigation("UserPointShopItemsInventory");
                });

            modelBuilder.Entity("SteamHub.Api.Entities.User", b =>
                {
                    b.Navigation("StoreTransactions");

                    b.Navigation("UserPointShopItemsInventory");
                });
#pragma warning restore 612, 618
        }
    }
}
